# basic options
title: ANUBHAB PATTANAYAK
author:
  name: Anubhab Pattanayak
  email: anubhab@mse.ac.in
description: Welcome to my website!

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
